### ISSUE TITLE
Bug in walkVals function expanding the possible values in a compoundMultiIndex

### ISSUE THREAD

**Issue by WingGithub** [hashicorp/go-memdb#106]
When inserting an entry into a table with a compound multi index with a few multi indexers the walkVals function tries to expand all the possible values for a given entry which has multiple string slices. There is a bug in the recursive algoritm. In the example there is 36 possible values for the criterias index with 12 each of the last values of 301, 302 and 303 but this is not the case when the values are expanded.
```
package main

import (
"fmt"
"github.com/hashicorp/go-memdb"
)

func main() {
// Create a sample struct
type LineItem struct {
Id int
CreativeType string
DeviceType []string
InventoryType []string
Partners []string
Dayparts []string
}

// Create the DB schema
schema := &memdb.DBSchema{
	Tables: map[string]*memdb.TableSchema{
		"lineItem": &memdb.TableSchema{
			Name: "lineItem",
			Indexes: map[string]*memdb.IndexSchema{
				"id": &memdb.IndexSchema{
					Name:    "id",
					Unique:  true,
					Indexer: &memdb.IntFieldIndex{Field: "Id"},
				},
				"criterias": &memdb.IndexSchema{
					Name:   "criterias",
					Unique: false,
					Indexer: &memdb.CompoundMultiIndex{
						Indexes: []memdb.Indexer{
							&memdb.StringFieldIndex{Field: "CreativeType"},
							&memdb.StringSliceFieldIndex{Field: "DeviceType"},
							&memdb.StringSliceFieldIndex{Field: "InventoryType"},
							&memdb.StringSliceFieldIndex{Field: "Partners"},
							&memdb.StringSliceFieldIndex{Field: "Dayparts"},
						},
					},
				},
			},
		},
	},
}

err := schema.Validate()
if err != nil {
	panic(err)
}

// Create a new data base
db, err := memdb.NewMemDB(schema)
if err != nil {
	panic(err)
}

// Create a write transaction
txn := db.Txn(true)

// Insert some people
li := []*LineItem{
	{
		Id:            1045,
		CreativeType:  "video",
		DeviceType:    []string{"tv", "desktop", "mobile"},
		InventoryType: []string{"web", "app"},
		Partners:      []string{"microsoft", "google"},
		Dayparts:      []string{"301", "302", "303"},
	},
}
for _, p := range li {
	fmt.Printf("%+v\n", p)
	if err := txn.Insert("lineItem", p); err != nil {
		panic(err)
	}
}

// Commit the transaction
txn.Commit()

// Create read-only transaction
txn = db.Txn(false)
defer txn.Abort()

// Lookup by email
raw, err := txn.First("lineItem", "id", 1045)
if err != nil {
	panic(err)
}

// Say hi!
fmt.Printf("Hello %d!\n", raw.(*LineItem).Id)

// List by criterias index
it, err := txn.Get("lineItem", "criterias", "video", "tv", "app", "microsoft", "303")
if err != nil {
	panic(err)
}

fmt.Print("Found:")
for obj := it.Next(); obj != nil; obj = it.Next() {
	p := obj.(*LineItem)
	fmt.Printf("  %v\n", p)
}

// What? Can't find it?
it, err = txn.Get("lineItem", "criterias", "video", "tv", "app", "microsoft", "301")
if err != nil {
	panic(err)
}

fmt.Print("Found:")
for obj := it.Next(); obj != nil; obj = it.Next() {
	p := obj.(*LineItem)
	fmt.Printf("  %v\n", p)
}

}
```

**Comment by WingGithub** [comment]
When inserting an entry into a table with a compound multi index with a few multi indexers the walkVals function tries to expand all the possible values for a given entry which has multiple string slices. There is a bug in the recursive algoritm. In the example there is 36 possible values for the criterias index with 12 each of the last values of 301, 302 and 303 but this is not the case when the values are expanded.

package main

import (
	"fmt"
	"github.com/hashicorp/go-memdb"
)

func play() {
	// Create a sample struct
	type LineItem struct {
		Id            int
		CreativeType  string
		DeviceType    []string
		InventoryType []string
		Partners      []string
		Dayparts      []string
	}

	// Create the DB schema
	schema := &memdb.DBSchema{
		Tables: map[string]*memdb.TableSchema{
			"lineItem": &memdb.TableSchema{
				Name: "lineItem",
				Indexes: map[string]*memdb.IndexSchema{
					"id": &memdb.IndexSchema{
						Name:    "id",
						Unique:  true,
						Indexer: &memdb.IntFieldIndex{Field: "Id"},
					},
					"criterias": &memdb.IndexSchema{
						Name:   "criterias",
						Unique: false,
						Indexer: &memdb.CompoundMultiIndex{
							Indexes: []memdb.Indexer{
								&memdb.StringFieldIndex{Field: "CreativeType"},
								&memdb.StringSliceFieldIndex{Field: "DeviceType"},
								&memdb.StringSliceFieldIndex{Field: "InventoryType"},
								&memdb.StringSliceFieldIndex{Field: "Partners"},
								&memdb.StringSliceFieldIndex{Field: "Dayparts"},
							},
						},
					},
				},
			},
		},
	}

	err := schema.Validate()
	if err != nil {
		panic(err)
	}

	// Create a new data base
	db, err := memdb.NewMemDB(schema)
	if err != nil {
		panic(err)
	}

	// Create a write transaction
	txn := db.Txn(true)

	// Insert some people
	li := []*LineItem{
		{
			Id:            1045,
			CreativeType:  "video",
			DeviceType:    []string{"tv", "desktop", "mobile"},
			InventoryType: []string{"web", "app"},
			Partners:      []string{"microsoft", "google"},
			Dayparts:      []string{"301", "302", "303"},
		},
	}
	for _, p := range li {
		fmt.Printf("%+v\n", p)
		if err := txn.Insert("lineItem", p); err != nil {
			panic(err)
		}
	}

	// Commit the transaction
	txn.Commit()

	// Create read-only transaction
	txn = db.Txn(false)
	defer txn.Abort()

	// Lookup by email
	raw, err := txn.First("lineItem", "id", 1045)
	if err != nil {
		panic(err)
	}

	// Say hi!
	fmt.Printf("Hello %d!\n", raw.(*LineItem).Id)

	// List by criterias index
	it, err := txn.Get("lineItem", "criterias", "video", "tv", "app", "microsoft", "303")
	if err != nil {
		panic(err)
	}

	fmt.Print("Found:")
	for obj := it.Next(); obj != nil; obj = it.Next() {
		p := obj.(*LineItem)
		fmt.Printf("  %v\n", p)
	}

	// What? Can't find it?
	it, err = txn.Get("lineItem", "criterias", "video", "tv", "app", "microsoft", "301")
	if err != nil {
		panic(err)
	}

	fmt.Print("Found:")
	for obj := it.Next(); obj != nil; obj = it.Next() {
		p := obj.(*LineItem)
		fmt.Printf("  %v\n", p)
	}
}

**Comment by WingGithub** [comment]
Looks like this is the same issue in #72 and the fix is also mentioned in there and it seems to work. This seems like an important issue and the fix is available, why isn't the fix incorporated?

**Comment by kisunji** [comment]
Closed by https://github.com/hashicorp/go-memdb/pull/108
