### ISSUE TITLE
Map[string]interface{} instead of structs.

### ISSUE THREAD

**Issue by tpoxa** [hashicorp/go-memdb#116]
I am just curious is that a good idea to have the support of Map[string]interface{} for Insert instead of a struct? I  want to build fully configurable in-memory storage and statically typed structs make this impossible. 
Thanks.

**Comment by lthibault** [comment]
@tpoxa I don't think there is anything preventing you from using `map[string]any`.  I believe the only extra step is to write your own indexer, which is fairly straightforward.

**Comment by tpoxa** [comment]
Thanks @lthibault
