### ISSUE TITLE
Race condition on db.root

### ISSUE THREAD

**Issue by floridoo** [hashicorp/go-memdb#12]
**How to reproduce:**
* open and commit a write transaction in one goroutine
* use a read transaction in a different goroutine

**Example**: https://gist.github.com/floridoo/2621afccc55130a5334c (run with --race)

Race condition between:
* this read of `db.root` in `MemDB.Txn()`: [memdb.go#L48](https://github.com/hashicorp/go-memdb/blob/31949d523ade8a236956c6f1761e9dcf902d1638/memdb.go#L48)
* this write of `db.root` in `Txn.Commit()`: [txn.go#L116](https://github.com/hashicorp/go-memdb/blob/31949d523ade8a236956c6f1761e9dcf902d1638/txn.go#L116)

**Comment by armon** [comment]
Fixed by #14. Thanks!
