### ISSUE TITLE
Can you add a IntFieldIndex?

### ISSUE THREAD

**Issue by shenwei356** [hashicorp/go-memdb#16]
Hi @armon , can you add IntFieldIndex or UintFieldIndex, that would save a lot of memory for huge database.

**Comment by shenwei356** [comment]
For my case, I'd want to store struct like this.
```
type uint2uint struct {
        k uint
        v uint
}
```

There are hundreds of millions records to be stored, so, I think a `IntFieldIndex` or `UintFieldIndex` would help.

From the code of `Indexer` interface,  `FromObject` and `FromArgs` return `[]byte`, so space of indexer may not reduce, but the space of data may be much smaller.

**Comment by armon** [comment]
@shenwei356 We would accept a PR that adds support for an integer field index, the `binary` package can be used to efficiently represent integers as byte slices for indexing as well (https://golang.org/pkg/encoding/binary/#ByteOrder).

**Comment by shenwei356** [comment]
thanks @armon, I'll try
