### ISSUE TITLE
What's memdb.WatchSet do?

### ISSUE THREAD

**Issue by matthewmueller** [hashicorp/go-memdb#32]
Apologies for the noob question, but I've been trying to figure it out for the last 20 or so minutes. I'm noticing it being used all around Nomad and Consul codebases, but I'm not really seeing it be used for anything, other than creating the watchset and adding items to the set. 

Is it sort of like a WaitGroup for synchronization? Or used to inform subscribers of changes? Or something else entirely? :-)

**Comment by slackpad** [comment]
Hi @matthewmueller it is used to inform subscribers of changes, and is the mechanism behind [blocking queries](https://www.consul.io/api/index.html#blocking-queries). Here's where the watch set actually gets used - https://github.com/hashicorp/consul/blob/v0.8.3/consul/rpc.go#L402-L417.

So when the called performs the query (`err := fn(ws, state)`) in that example, the `WatchSet` is filled with channels for every item that was returned (often a single channel can summarize a whole range of entries, so it's not 1:1 with the items returned). If the caller's passed-in index matches what is queried, then `ws.Watch(timeout.C)` will block until something in the set is changed, or a timeout occurs. Hope that helps!

**Comment by matthewmueller** [comment]
Awesome, that makes way more sense. Thanks for your help @slackpad!
