### ISSUE TITLE
google app engine Failed parsing input: parser: bad import "unsafe"

### ISSUE THREAD

**Issue by ahmadissa** [hashicorp/go-memdb#44]
go-app-builder: Failed parsing input: parser: bad import "unsafe" in github.com/hashicorp/go-memdb/filter.go from GOPATH

**Comment by slackpad** [comment]
Hi @ahmadissa it doesn't look like filter.go actually imports that. Do you have a locally-modified version in your GOPATH?

**Comment by ahmadissa** [comment]
Thanks for the reply,
I have not modified it, to make sure i have done the below:
```
 git reset --hard
HEAD is now at 75ff996 Merge pull request #42 from blockloop/master
```

**Comment by ahmadissa** [comment]
only importing the library causing this problem

`_ "github.com/hashicorp/go-memdb"`

**Comment by slackpad** [comment]
Ah it looks like Google App Engine removes the `unsafe` package - https://blog.golang.org/go-and-google-app-engine.

> The runtime provides the full Go language and almost all the standard libraries, except for a few things that don’t make sense in the App Engine environment. For instance, there is no unsafe package and the syscall package is trimmed. (The implementation uses an expanded version of the setup in the Go Playground on golang.org.)

I think you'd have to patch go-memdb to make it work with Google App Engine (I'm not an expert there, but it looks like that from a quick look at the docs). The atomic swap is used all over the place during transactions, so I don't think we'd want to take a change that removes it, but you could make a fork and replace `unsafe` with a mutex basically to make it less performant but safe. Hope that helps!
