### ISSUE TITLE
Is it possible to do range iterations ?

### ISSUE THREAD

**Issue by atrniv** [hashicorp/go-memdb#46]
Hi,

I was wondering if it's possible to do range iterations in go-memdb.
If you were using this as an in-memory database it should be a fairly common operation I'm assuming.

For example ranging over all keys starting with "a" until "c". The only option I see is a prefix based query or an exact match. 
How hard would it be to extend this to allow range queries ?

**Comment by vassudanagunta** [comment]
Not sure if was implemented with your request in mind, but it sure looks like it will be: hashicorp/go-immutable-radix#24
