### ISSUE TITLE
Boolean indexer

### ISSUE THREAD

**Issue by jorygeerts** [hashicorp/go-memdb#69]
I needed to index on a boolean field (or rather, I needed a boolean as part of a compound index) so I created a `BoolFieldIndex` for that.

If there is any interest, I'd be happy to create a PR that adds this index.

If there was already a good way to index on a boolean field that I've overlooked, I'd like to hear about it so I can delete my own code and use the pre-existing solution instead.

**Comment by jefferai** [comment]
Hi there,

I couldn't comment on whether the community at large thinks this is a good idea or not, but I'd say -- PR it! If you already have the code, might as well  :-)
