### ISSUE TITLE
In-place object update doesn't delete old index values

### ISSUE THREAD

**Issue by mullakhmetov** [hashicorp/go-memdb#76]
If you you are trying to in-place update (via `txn.Insert`) already inserted object, the old no longer relevant values are not deleted from index.

I'm not sure is it bug or known implementation feature. Here is the test to reproduce:

```
func TestTxn_InsertUpdate_Inplace(t *testing.T) {
	db := testDB(t)
	txn := db.Txn(true)

	oldV := "abc"
	newV := "xyz"

	// Create object
	obj := &TestObject{
		ID:  "my-object",
		Foo: oldV,
		Qux: []string{"abc1", "abc2"},
	}
	err := txn.Insert("main", obj)
	if err != nil {
		t.Fatalf("err: %v", err)
	}

	// Insert it
	raw, err := txn.First("main", "foo", obj.Foo)
	if err != nil {
		t.Fatalf("err: %v", err)
	}

	if raw != obj {
		t.Fatalf("bad: %#v %#v", raw, obj)
	}

	// Update it in-place
	obj.Foo = newV

	// Trying to reindex object
	err = txn.Insert("main", obj)
	if err != nil {
		t.Fatalf("err: %v", err)
	}

	// Lookup of the new value
	raw, err = txn.First("main", "foo", newV)
	if err != nil {
		t.Fatalf("err: %v", err)
	}

	if raw != obj {
		t.Fatalf("bad: %#v %#v", raw, obj)
	}

	// Lookup of the old value. Should fail, but it does not
	raw, err = txn.First("main", "foo", oldV)
	if err != nil {
		t.Fatalf("err: %v", err)
	}

	if raw != nil {
		t.Fatalf("bad: %#v", raw)
	}
}
```

The reason for this behavior is that you you calculate existing index values (line 243 in snippet below) from indexed object (which was updated), so you always get `valExist` equals to `val[i]` and never delete the truly old existing value from index.

https://github.com/hashicorp/go-memdb/blob/ac8c839d3bac603f96bbb715e0d267c565567d0f/txn.go#L234-L268

**Comment by mitchellh** [comment]
This is being fixed by a docs update. For memdb, objects are not safe to be mutated once they're inserted. You must perform a copy. We can't detect this for you without significant performance penalties so we opted to improve the docs around it.
