### ISSUE TITLE
How to perform searching in database by multiple fields if one of them is optional? 

### ISSUE THREAD

**Issue by timurkhametov** [hashicorp/go-memdb#98]
Hello there. Currently, I'm implementing a lookup mechanism to search data in an in-memory database. But I bumped into a problem to perform searching by several fields. Let's say I have the following structure stored in a database:

```go
type Person struct {
   FirstName         string
   SecondName    string
   LastName         string
}
```

And I would like to search people by either first name or second name or last name or use them together. Compound indexes don't work for this case since I can search let's say only by first name and other search criteria will be empty. Also I can't create separate index for each field since go-mem doesn't support the search by several indexes. Do you guys know any workarounds or how can I perform searching by several fields?

**Comment by dnephin** [comment]
Hello, thank you for your interest in go-memdb!

If I am understanding your question correctly, it sounds like what you'll need is a [MultiIndex](https://pkg.go.dev/github.com/hashicorp/go-memdb#MultiIndexer) for "search people by either first name or second name or last name".

I believe you saw my previous comment about custom indexes (https://github.com/hashicorp/go-memdb/issues/97#issuecomment-825772929), but I'll link it again here as context for others.

In this case, a MultiIndex would look something like this:

```go
type anyNameIndexer struct{}

func (anyNameIndexer) FromArgs(args ...interface{}) ([]byte, error) {
	if len(args) != 1 {
		return nil, fmt.Errorf("wrong number of args %d, expected 1", len(args))
	}
	s, ok := args[0].(string)
	if !ok {
		return nil, fmt.Errorf("wrong type for arg %T, expected string", args[0])
	}
	return append([]byte(s), 0), nil
}


func (anyNameIndexer) FromObject(raw interface{}) (bool, [][]byte, error) {
	p, ok := raw.(Person)
	if !ok {
		return false, nil, fmt.Errorf("wrong type for arg %T, expected Person", raw)
	}

	result := make([][]byte, 3)
	result[0] = append([]byte(p.FirstName), 0)
	result[1] = append([]byte(p.SecondName), 0)
	result[2] = append([]byte(p.LastName), 0)
	return true, result, nil
}
```

Querying that index with a name will return any person where one of the names matches.

For "use them together" you could add more entries to the `result` if you wanted, for example you could index `p.FirstName + " " + p.LastName"` to match them together.

**Comment by timurkhametov** [comment]
@dnephin, thank you very much for the quick reply! Just want to clarify, does it mean that if I want to use all available combinations I should write something like that:

```go
result[0] = append([]byte(p.FirstName), 0)
result[1] = append([]byte(p.SecondName), 0)
result[2] = append([]byte(p.LastName), 0)

result[3] = append([]byte(p.FirstName + " " + p.SecondName), 0)
result[4] = append([]byte(p.FirstName + " " + p.LastName), 0)
result[5] = append([]byte(p.SecondName + " " + p.LastName), 0)

result[6] = append([]byte(p.FirstName + " " + p.SecondName + " " + p.LastName), 0)
```

**Comment by timurkhametov** [comment]
Well, I have written the following helper function in case somebody comes across the same issue:

```go
const fieldSeparator = "_"

// Enumerate all available combinations of the passed elements.
// E.g. having the following set of elements { "1", "2", "3" },
// method will return { "1", "2", "1_2", "3", "1_3", "2_3", "1_2_3" }
func getCombinations(elements ...string) []string {
	prevSlice := make([]string, 1)

	for i := range elements {
		newSlice := make([]string, len(prevSlice))
		copy(newSlice, prevSlice)

		for j := 0; j < len(newSlice); j++ {
			newSlice[j] = concatFields(newSlice[j], elements[i])
		}

		prevSlice = append(prevSlice, newSlice...)
	}

	return prevSlice[1:] // have to omit the first element since it's empty
}

func concatFields(fields ...string) string {
	return strings.Trim(strings.Join(fields, fieldSeparator), fieldSeparator)
}
```

And then this can be used in `FromObject`:

```go
combinations := getCombinations(p.FirstName, p.SecondName, p.LastName)
values := make([][]byte, 0, len(combinations))

for i := range combinations {
	val := combinations[i]
	// Add the null character as a terminator
	val += "\x00"
	values = append(values, []byte(val))
}
```

**Comment by timurkhametov** [comment]
@dnephin thank you once again for your invaluable help!
